application: metatictactoe
version: 2
runtime: python
api_version: 1

inbound_services:
- channel_presence

handlers:
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /.*
  script: Main.py
